export const QRDetails = [
  {
    id: 1001,
    title: "Design 1",
    price: 1,
    catergory: "Muslim",
    path: "https://i.ibb.co/PmmPjWP/qr1.png",
  },
  {
    id: 1002,
    title: "Design 2",
    price: 1,
    catergory: "Muslim",
    path: "https://i.ibb.co/60jtXyL/qr2.png",
  },
  {
    id: 1003,
    title: "Design 3",
    price: 1,
    catergory: "Muslim",
    path: "https://i.ibb.co/L1cFBsf/qr3.png",
  },
  {
    id: 1004,
    title: "Design 4",
    price: 1,
    catergory: "Muslim",
    path: "https://i.ibb.co/3CTBCVL/qr4.png",
  },
  {
    id: 1005,
    title: "Design 5",
    price: 1,
    catergory: "Muslim",
    path: "https://i.ibb.co/9qNfb0d/qr5.jpg",
  },
  {
    id: 1006,
    title: "Design 6",
    price: 1,
    catergory: "Muslim",
    path: "https://i.ibb.co/RcGydjW/qr6.jpg",
  },
  {
    id: 1007,
    title: "Design 7",
    price: 1,
    catergory: "Muslim",
    path: "https://i.ibb.co/6FTHmXJ/qr7.jpg",
  },
  {
    id: 1008,
    title: "Design 8",
    price: 1,
    catergory: "Muslim",
    path: "https://i.ibb.co/7gLNTHN/qr10.jpg",
  },
  {
    id: 1009,
    title: "Design 9",
    price: 1,
    catergory: "Muslim",
    path: "https://i.ibb.co/kS6vkq4/qr27.jpg",
  },
  {
    id: 10010,
    title: "Design 10",
    price: 1,
    catergory: "Muslim",
    path: "https://i.ibb.co/7gLNTHN/qr10.jpg",
  },
  {
    id: 10011,
    title: "Design 11",
    price: 1,
    catergory: "Muslim",
    path: "https://i.ibb.co/yggm4v8/qr26.jpg",
  },
  {
    id: 10012,
    title: "Design 12",
    price: 1,
    catergory: "Muslim",
    path: "https://i.ibb.co/VL7gXbD/qr25.jpg",
  },
  {
    id: 10013,
    title: "Design 13",
    price: 1,
    catergory: "Muslim",
    path: "https://i.ibb.co/X2Yb0Gx/qr24.jpg",
  },
  {
    id: 10014,
    title: "Design 14",
    price: 1,
    catergory: "Muslim",
    path: "https://i.ibb.co/2NcmysX/qr23.jpg",
  },
  {
    id: 10015,
    title: "Design 15",
    price: 1,
    catergory: "Muslim",
    path: "https://i.ibb.co/C6jz482/qr22.png",
  },
  {
    id: 10016,
    title: "Design 16",
    price: 1,
    catergory: "Muslim",
    path: "https://i.ibb.co/qWxcYXL/qr21.png",
  },
  {
    id: 10017,
    title: "Design 17",
    price: 1,
    catergory: "Muslim",
    path: "https://i.ibb.co/MSb8NBM/qr20.png",
  },
  {
    id: 10018,
    title: "Design 18",
    price: 1,
    catergory: "Muslim",
    path: "https://i.ibb.co/jbs9MXH/qr19.png",
  },
  {
    id: 10019,
    title: "Design 19",
    price: 1,
    catergory: "Muslim",
    path: "https://i.ibb.co/hsnt3GB/qr18.jpg",
  },
  {
    id: 10020,
    title: "Design 20",
    price: 1,
    catergory: "Muslim",
    path: "https://i.ibb.co/f4DrCZp/qr14.png",
  },
  {
    id: 10021,
    title: "Design 21",
    price: 1,
    catergory: "Muslim",
    path: "https://i.ibb.co/R6x6zBc/qr13.png",
  },
  {
    id: 10022,
    title: "Design 22",
    price: 1,
    catergory: "Muslim",
    path: "https://i.ibb.co/6mDDzHK/qr12.png",
  },
  {
    id: 10023,
    title: "Design 23",
    price: 1,
    catergory: "Muslim",
    path: "https://i.ibb.co/ZByMX9h/qr11.jpg",
  },
  {
    id: 10024,
    title: "Design 24",
    price: 1,
    catergory: "Muslim",
    path: "https://i.ibb.co/PMGrK09/qr17.jpg",
  },
];

export const serviceDetails = [
  {
    id: 2000,
    title: "Sweet",
    price: "₹ 1",
    path: "/Images/Service/Courier.jpg",
    des: "This card is for this this this",
    cat: "Nature",
  },
  {
    id: 2001,
    title: "Sweet",
    price: "₹ 1",
    path: "/Images/Service/fLOWER.webp",
    des: "This card is for this this this",
    cat: "Nature",
  },
  {
    id: 2002,
    title: "Sweet",
    price: "₹ 1",
    path: "/Images/Service/PHOTOGRAPHY.png",
    des: "This card is for this this this",
    cat: "Nature",
  },
  {
    id: 2003,
    title: "Sweet",
    price: "₹ 1",
    path: "/Images/Service/qr.png",
    des: "This card is for this this this",
    cat: "Nature",
  },
  {
    id: 2004,
    title: "Sweet",
    price: "₹ 1",
    path: "/Images/Service/hotel.jpg",
    des: "This card is for this this this",
    cat: "Nature",
  },
];

export const videoThumbnailDetails = [
  {
    id: 1000,
    title: "Sweet",
    price: "₹ 1",
    path: "/Images/Video/VIDEO1.png",
    des: "This card is for this this this",
    cat: "Nature",
  },
  {
    id: 1001,
    title: "Sweet",
    price: "₹ 1",
    path: "/Images/Video/VIDEO2.png",
    des: "This card is for this this this",
    cat: "Nature",
  },
  {
    id: 1002,
    title: "Sweet",
    price: "₹ 1",
    path: "/Images/Video/VIDEO3.png",
    des: "This card is for this this this",
    cat: "Nature",
  },
  {
    id: 1003,
    title: "Sweet",
    price: "₹ 1",
    path: "/Images/Video/VIDEO4.png",
    des: "This card is for this this this",
    cat: "Nature",
  },
  {
    id: 1004,
    title: "Sweet",
    price: "₹ 1",
    path: "/Images/Video/VIDEO5.png",
    des: "This card is for this this this",
    cat: "Nature",
  },
  {
    id: 1005,
    title: "Sweet",
    price: "₹ 1",
    path: "/Images/Video/VIDEO6.png",
    des: "This card is for this this this",
    cat: "Nature",
  },
];

export const cardDetails = [
  {
    id: "card1",
    title: "Elegant Vows",
    cat: "Muslim",
    price: 20,
    des: "Elegant ivory card with gold foil lettering and intricate lace patterns.",
    path: "https://i.ibb.co/NFhN5J1/card1.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card2",
    title: "Joyful Union",
    cat: "Muslim",
    price: 15,
    des: "Rustic kraft paper invitation with hand-drawn floral accents.",
    path: "https://i.ibb.co/5r0HWLx/card2.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card3",
    title: "Sacred Bond",
    cat: "Muslim",
    price: 10,
    des: "Modern minimalist design with clean lines and a monochrome color scheme.",
    path: "https://i.ibb.co/y8MjkrY/card3.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card4",
    title: "Timeless Love",
    cat: "Muslim",
    price: 13,
    des: "Vintage-inspired card with delicate watercolor florals and cursive script.",
    path: "https://i.ibb.co/vVBSW0k/card5-2.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card5",
    title: "Blissful Beginnings",
    cat: "Muslim",
    price: 46,
    des: "Chic black and white invitation with bold typography and geometric shapes.",
    path: "https://i.ibb.co/RBbfwLz/card5.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card6",
    title: "Pure Romance",
    cat: "Muslim",
    price: 14,
    des: "Classic navy and gold invitation with a timeless monogram.",
    path: "https://i.ibb.co/By8wF1J/card6.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card7",
    title: "Eternal Bliss",
    cat: "Muslim",
    price: 19,
    des: "Whimsical card featuring watercolor illustrations and playful fonts.",
    path: "https://i.ibb.co/4pBdt7r/card7.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card8",
    title: "Serene Ceremony",
    cat: "Muslim",
    price: 50,
    des: "Luxurious card with velvet touch finish and gold embossing.",
    path: "https://i.ibb.co/nCvLf7z/card9.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card9",
    title: "Classic Love",
    cat: "Muslim",
    price: 50,
    des: "Romantic blush pink invitation with rose gold foil details.",
    path: "https://i.ibb.co/khWKkP2/card10.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card10",
    title: "Heartfelt Union",
    cat: "Muslim",
    price: 50,
    des: "Tropical-themed card with vibrant palm leaves and exotic flowers",
    path: "https://i.ibb.co/tK0TvKC/card11.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card11",
    title: "Divine Love",
    cat: "Muslim",
    price: 50,
    des: "Elegant emerald green invitation with gold accents and a satin ribbon.",
    path: "https://i.ibb.co/crTmJtY/card12.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card12",
    title: "Graceful Union",
    cat: "Muslim",
    price: 50,
    des: "Art deco-inspired design with metallic accents and bold patterns.",
    path: "https://i.ibb.co/crstXWq/card13.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card13",
    title: "True Love",
    cat: "Muslim",
    price: 50,
    des: "Simple kraft paper card with twine and a wax seal",
    path: "https://i.ibb.co/j4mBZzb/card14.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card14",
    title: "Regal Wedding",
    cat: "Muslim",
    price: 50,
    des: "Nautical-themed invitation with navy stripes and anchor motifs.",
    path: "https://i.ibb.co/w6bJYth/card15.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card15",
    title: "Happy Hearts",
    cat: "Muslim",
    price: 50,
    des: "Sophisticated marble design with gold foil details.",
    path: "https://i.ibb.co/fXz3cwt/card16.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card16",
    title: "Sweet Vows",
    cat: "Muslim",
    price: 50,
    des: "Bohemian-style card with dreamcatcher illustrations and earthy tones.",
    path: "https://i.ibb.co/Fgbrq4x/card16-2.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card17",
    title: " Beautiful Beginnings",
    cat: "Muslim",
    price: 50,
    des: "Glamorous glittery gold invitation with a classic script font.",
    path: "https://i.ibb.co/SmHVPXV/card17.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card18",
    title: "Cherished Moments",
    cat: "Muslim",
    price: 50,
    des: "Eco-friendly card made from recycled paper with botanical prints.",
    path: "https://i.ibb.co/5Lyc1v0/card18.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card19",
    title: "Precious Love",
    cat: "Muslim",
    price: 50,
    des: "Fairy tale-inspired design with enchanted forest illustrations.",
    path: "https://i.ibb.co/tzCcrpq/card19.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card20",
    title: "Love Knot",
    cat: "Muslim",
    price: 50,
    des: "Elegant cream and gold invitation with intricate laser-cut details.",
    path: "https://i.ibb.co/cDNLWgr/card20.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card21",
    title: "Serene Vows",
    cat: "Muslim",
    price: 50,
    des: "Floral watercolor card with a delicate border and elegant script.",
    path: "https://i.ibb.co/Vt347b5/card21.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card22",
    title: "Blissful Union",
    cat: "Muslim",
    price: 50,
    des: "Modern acrylic invitation with sleek typography.",
    path: "https://i.ibb.co/Rpp6C92/card22.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card23",
    title: "Perfect Pair",
    cat: "Muslim",
    price: 50,
    des: "Rustic wood veneer card with engraved details.",
    path: "https://i.ibb.co/WWztyDn/card24.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card24",
    title: " Simple Elegance",
    cat: "Muslim",
    price: 50,
    des: "Sophisticated grey and silver invitation with a minimalist design.",
    path: "https://i.ibb.co/RpLmqkF/card23.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card25",
    title: " Pure Joy",
    cat: "Muslim",
    price: 50,
    des: "Tropical destination wedding invitation with vibrant hibiscus flowers.",
    path: "https://i.ibb.co/Qjp1Z7G/card25.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card26",
    title: "Golden Moments",
    cat: "Muslim",
    price: 50,
    des: "Whimsical balloon-themed card with colorful illustrations.",
    path: "https://i.ibb.co/GCkLJZd/card27.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card27",
    title: "Sacred Promise",
    cat: "Muslim",
    price: 50,
    des: "Vintage postcard-style invitation with a nostalgic feel.",
    path: "https://i.ibb.co/dgWvzqk/card26.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card28",
    title: " Lovely Bond",
    cat: "Muslim",
    price: 50,
    des: "Elegant pearl-finished card with lace patterns and satin bow.",
    path: "https://i.ibb.co/4KfPxJh/card28.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card29",
    title: "Joyous Journey",
    cat: "Muslim",
    price: 50,
    des: "Bold red and gold invitation with a traditional Asian design.",
    path: "https://i.ibb.co/9YB7wMY/card29.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card30",
    title: "Sweet Love",
    cat: "Muslim",
    price: 50,
    des: "Charming cottage-themed card with hand-painted flowers.",
    path: "https://i.ibb.co/R3fK1r3/card30.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card31",
    title: "Radiant Hearts",
    cat: "Muslim",
    price: 50,
    des: "Luxurious velvet card with gold foil stamping.",
    path: "https://i.ibb.co/fXx26Hp/card31.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card32",
    title: "Enchanted Love",
    cat: "Muslim",
    price: 50,
    des: "Minimalist kraft paper invitation with calligraphy.",
    path: "https://i.ibb.co/hBN889q/card32.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card33",
    title: "Elegant Affair",
    cat: "Muslim",
    price: 50,
    des: "Elegant scroll invitation with gold accents and a ribbon tie.",
    path: "https://i.ibb.co/c12NpWT/card33.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card34",
    title: "Love’s Embrace",
    cat: "Muslim",
    price: 50,
    des: "Rustic burlap card with lace and twine details.",
    path: "https://i.ibb.co/cx4XWpH/card34.png",
    path2: "",
    path3: "",
  },
  {
    id: "card35",
    title: " Dreamy Vows",
    cat: "Muslim",
    price: 50,
    des: "Classic black-tie invitation with sleek black and white design.",
    path: "https://i.ibb.co/rFH3wD0/card35.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card36",
    title: "Serene Union",
    cat: "Muslim",
    price: 50,
    des: "Nautical navy and white card with anchor details.",
    path: "https://i.ibb.co/GdG21MH/card36.png",
    path2: "",
    path3: "",
  },
  {
    id: "card37",
    title: "Charming Ceremony",
    cat: "Muslim",
    price: 50,
    des: "Botanical-themed invitation with lush greenery illustrations.",
    path: "https://i.ibb.co/1K2yNJD/card37.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card38",
    title: "Elegant Love",
    cat: "Muslim",
    price: 50,
    des: "Vintage lace overlay card with pearl accents.",
    path: "https://i.ibb.co/xfNHGXS/card38.png",
    path2: "",
    path3: "",
  },
  {
    id: "card39",
    title: "Heartfelt Ceremony",
    cat: "Muslim",
    price: 50,
    des: "Modern geometric design with gold foil and bold typography.",
    path: "https://i.ibb.co/ryPgfJt/card39.png",
    path2: "",
    path3: "",
  },
  {
    id: "card40",
    title: " Regal Union",
    cat: "Muslim",
    price: 50,
    des: "Floral laser-cut invitation with a blush pink ribbon.",
    path: "https://i.ibb.co/tpGJJz1/card40.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card41",
    title: "Sacred Ceremony",
    cat: "Muslim",
    price: 50,
    des: "Elegant damask pattern card with silver foil.",
    path: "https://i.ibb.co/FgN06HL/card43.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card42",
    title: "Joyful Hearts",
    cat: "Muslim",
    price: 50,
    des: "Whimsical garden-themed card with colorful floral illustrations.",
    path: "https://i.ibb.co/5KGdp2F/card41.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card43",
    title: "Blissful Ceremony",
    cat: "Muslim",
    price: 50,
    des: "Sophisticated navy and gold invitation with a monogrammed seal.",
    path: "https://i.ibb.co/7RwqTSB/card42.jpg",
    path2: "",
    path3: "",
  },
  {
    id: "card44",
    title: "Lovely Vows",
    cat: "Muslim",
    price: 50,
    des: "Rustic kraft paper card with botanical prints and twine.",
    path: "https://i.ibb.co/bF8Jb8r/card45.png",
    path2: "",
    path3: "",
  },
  {
    id: "card45",
    title: " Pure Bliss",
    cat: "Muslim",
    price: 50,
    des: "Glamorous glitter invitation with elegant script font.",
    path: "https://i.ibb.co/T8X2c4w/card46.png",
    path2: "",
    path3: "",
  },
  {
    id: "card46",
    title: "Love’s Journey",
    cat: "Muslim",
    price: 50,
    des: "Minimalist white card with gold foil lettering.",
    path: "https://i.ibb.co/T8X2c4w/card46.png",
    path2: "",
    path3: "",
  },
  {
    id: "card47",
    title: "Happy Together",
    cat: "Muslim",
    price: 50,
    des: "Bohemian-inspired design with dreamcatcher and feathers.",
    path: "https://i.ibb.co/JRrXSTM/card47.png",
    path2: "",
    path3: "",
  },
  {
    id: "card48",
    title: "Sweet Harmony",
    cat: "Muslim",
    price: 50,
    des: "Rustic woodgrain invitation with delicate lace details.",
    path: "https://i.ibb.co/6nsvb77/card48.png",
    path2: "",
    path3: "",
  },
  {
    id: "card49",
    title: "Graceful Vows",
    cat: "Muslim",
    price: 50,
    des: "Modern typography-focused design with a monochrome palette.",
    path: "https://i.ibb.co/rpkLyVk/card49.png",
    path2: "",
    path3: "",
  },
  {
    id: "card50",
    title: "Eternal Love",
    cat: "Muslim",
    price: 50,
    des: "Chic marble card with rose gold accents.",
    path: "https://i.ibb.co/XZxTsCQ/card50.png",
    path2: "",
    path3: "",
  },
  {
    id: "card51",
    title: "Pure Union",
    cat: "Muslim",
    price: 50,
    des: "Vintage-inspired card with pastel florals and cursive script.",
    path: "https://i.ibb.co/3N9Bry6/card51.png",
    path2: "",
    path3: "",
  },
  {
    id: "card52",
    title: "Joyful Moments",
    cat: "Muslim",
    price: 50,
    des: "Elegant pearl-finished invitation with embossed patterns.",
    path: "https://i.ibb.co/MncN3r1/card53.png",
    path2: "",
    path3: "",
  },
  {
    id: "card53",
    title: "Lovely Together",
    cat: "Muslim",
    price: 50,
    des: "Nautical-themed card with stripes and rope details.",
    path: "https://i.ibb.co/xMHGQpR/card55.png",
    path2: "",
    path3: "",
  },
  {
    id: "card54",
    title: "Heartfelt Vows",
    cat: "Muslim",
    price: 50,
    des: "Floral watercolor invitation with a soft, romantic feel.",
    path: "https://i.ibb.co/ySvS55L/card56.png",
    path2: "",
    path3: "",
  },
  {
    id: "card55",
    title: "Sacred Hearts",
    cat: "Muslim",
    price: 50,
    des: "Luxurious velvet card with gold foil and satin ribbon.",
    path: "https://i.ibb.co/t3GJHt0/card57.png",
    path2: "",
    path3: "",
  },
  {
    id: "card56",
    title: "Blissful Together",
    cat: "Muslim",
    price: -1,
    des: "Rustic kraft paper card with hand-drawn illustrations.",
    path: "https://i.ibb.co/b15yjHm/card58.png",
    path2: "",
    path3: "",
  },
  {
    id: "card57",
    title: "Elegant Union",
    cat: "Muslim",
    price: 50,
    des: "Modern acrylic invitation with sleek, transparent design.",
    path: "https://i.ibb.co/K5JJbsp/card59.png",
    path2: "",
    path3: "",
  },
  {
    id: "card58",
    title: "True Joy",
    cat: "Muslim",
    price: 50,
    des: "Botanical-themed card with lush greenery and elegant script.",
    path: "https://i.ibb.co/VSL0hv7/card60.png",
    path2: "",
    path3: "",
  },
  {
    id: "card59",
    title: "Radiant Union",
    cat: "Muslim",
    price: 50,
    des: "Chic black and gold invitation with a sophisticated feel.",
    path: "https://i.ibb.co/s2MQKNc/card61.png",
    path2: "",
    path3: "",
  },
  {
    id: "card60",
    title: " Enchanted Hearts",
    cat: "Muslim",
    price: 50,
    des: "Whimsical garden party-themed card with colorful illustrations.",
    path: "https://i.ibb.co/t3N28hr/card62.png",
    path2: "",
    path3: "",
  },
  {
    id: "card61",
    title: "Charming Love",
    cat: "Muslim",
    price: 50,
    des: "Classic cream and gold invitation with a timeless design.",
    path: "https://i.ibb.co/Kyp6R7R/card63.png",
    path2: "",
    path3: "",
  },
  {
    id: "card62",
    title: "Lovely Moments",
    cat: "Muslim",
    price: 50,
    des: "Vintage lace overlay card with delicate details.",
    path: "https://i.ibb.co/7XNPwrd/card64.png",
    path2: "",
    path3: "",
  },
  {
    id: "card63",
    title: "Joyous Union",
    cat: "Muslim",
    price: 50,
    des: "Minimalist kraft paper invitation with simple typography.",
    path: "https://i.ibb.co/JpF5T2r/card65.png",
    path2: "",
    path3: "",
  },
  {
    id: "card64",
    title: " Pure Vows",
    cat: "Muslim",
    price: 50,
    des: "Elegant damask pattern card with silver foil accents.",
    path: "https://i.ibb.co/3dF23bY/card66.png",
    path2: "",
    path3: "",
  },
  {
    id: "card65",
    title: "Sweet Moments",
    cat: "Muslim",
    price: 50,
    des: "Rustic burlap and lace invitation with twine bow.",
    path: "https://i.ibb.co/tJxt89f/card67.png",
    path2: "",
    path3: "",
  },
  {
    id: "card66",
    title: "Heartfelt Love",
    cat: "Muslim",
    price: 50,
    des: "Glamorous glitter invitation with bold gold accents.",
    path: "https://i.ibb.co/4PD9Ynv/card68.png",
    path2: "",
    path3: "",
  },
  {
    id: "card129",
    title: " Sacred Bliss",
    cat: "Muslim",
    price: 50,
    des: "Modern monochrome design with clean lines and sleek typography.",
    path: "https://i.ibb.co/5v9SJnv/card69.png",
    path2: "",
    path3: "",
  },
  {
    id: "card67",
    title: "Elegant Together",
    cat: "Muslim",
    price: 50,
    des: "Floral watercolor card with soft, pastel hues.",
    path: "https://i.ibb.co/Gd3sx71/card70.png",
    path2: "",
    path3: "",
  },
  {
    id: "card68",
    title: " Joyful Promise",
    cat: "Muslim",
    price: 50,
    des: "Sophisticated navy and silver invitation with a monogram.",
    path: "https://i.ibb.co/YtPb89T/card71.png",
    path2: "",
    path3: "",
  },
  {
    id: "card69",
    title: "Dreamy Hearts",
    cat: "Muslim",
    price: 50,
    des: "Botanical-themed card with hand-drawn illustrations and earthy tones.",
    path: "https://i.ibb.co/Ws11mVm/card72.png",
    path2: "",
    path3: "",
  },
  {
    id: "card70",
    title: ". Love’s Harmony",
    cat: "Muslim",
    price: 50,
    des: "Vintage-inspired postcard invitation with a nostalgic design.",
    path: "https://i.ibb.co/DwFfhYg/card73.png",
    path2: "",
    path3: "",
  },
  {
    id: "card71",
    title: " Graceful Ceremony",
    cat: "Muslim",
    price: 50,
    des: "Chic marble card with gold foil and elegant script.",
    path: "https://i.ibb.co/kgjjHmr/card75.png",
    path2: "",
    path3: "",
  },
  {
    id: "card72",
    title: "Pure Together",
    cat: "Muslim",
    price: 50,
    des: "Rustic wood veneer invitation with engraved details.",
    path: "https://i.ibb.co/6wnsRzD/card76.png",
    path2: "",
    path3: "",
  },
  {
    id: "card73",
    title: "Happy Vows",
    cat: "Muslim",
    price: 50,
    des: "Modern acrylic card with a minimalist design",
    path: "https://i.ibb.co/5cJJTfg/card77.png",
    path2: "",
    path3: "",
  },
  {
    id: "card74",
    title: ". Radiant Bliss",
    cat: "Muslim",
    price: 50,
    des: "Whimsical balloon-themed invitation with playful illustrations.",
    path: "https://i.ibb.co/Pzmt5T9/card78.png",
    path2: "",
    path3: "",
  },
  {
    id: "card75",
    title: "Serene Hearts",
    cat: "Muslim",
    price: 50,
    des: "Elegant pearl-finished card with intricate lace patterns.",
    path: "https://i.ibb.co/w7b4ndh/card79.png",
    path2: "",
    path3: "",
  },
  {
    id: "card76",
    title: "Charming Vows",
    cat: "Muslim",
    price: 50,
    des: "Nautical-themed invitation with navy stripes and anchor motifs.",
    path: "https://i.ibb.co/P4SsVjk/card80.png",
    path2: "",
    path3: "",
  },
  {
    id: "card77",
    title: "Lovely Ceremony",
    cat: "Muslim",
    price: 50,
    des: "Floral watercolor card with a delicate border and cursive script.",
    path: "https://i.ibb.co/fphHPKm/card81.png",
    path2: "",
    path3: "",
  },
  {
    id: "card78",
    title: "Joyous Promise",
    cat: "Muslim",
    price: 50,
    des: "Sophisticated black and white design with bold typography.",
    path: "https://i.ibb.co/Thqj7nF/card82.png",
    path2: "",
    path3: "",
  },
  {
    id: "card79",
    title: "Heartfelt Union",
    cat: "Muslim",
    price: 50,
    des: "Vintage lace overlay card with pearl accents.",
    path: "https://i.ibb.co/kQdHgnG/card83.png",
    path2: "",
    path3: "",
  },
  {
    id: "card80",
    title: "Blissful Love",
    cat: "Muslim",
    price: 50,
    des: "Rustic kraft paper invitation with botanical prints and twine.",
    path: "https://i.ibb.co/hHp9Qtm/card84.png",
    path2: "",
    path3: "",
  },
  {
    id: "card81",
    title: "Elegant Moments",
    cat: "Muslim",
    price: 50,
    des: "Glamorous glitter invitation with elegant gold foil.",
    path: "https://i.ibb.co/74Kt4bN/card85.png",
    path2: "",
    path3: "",
  },
  {
    id: "card82",
    title: "True Together",
    cat: "Muslim",
    price: 50,
    des: "Minimalist white card with sleek, modern typography",
    path: "https://i.ibb.co/hZF9psH/card86.png",
    path2: "",
    path3: "",
  },
  {
    id: "card83",
    title: "Sacred Joy",
    cat: "Muslim",
    price: 50,
    des: "Bohemian-inspired invitation with dreamcatcher illustrations",
    path: "https://i.ibb.co/10ZbNQ2/card87.png",
    path2: "",
    path3: "",
  },
  {
    id: "card84",
    title: "Enchanted Ceremony",
    cat: "Muslim",
    price: 50,
    des: "Chic marble design with rose gold foil accents.",
    path: "https://i.ibb.co/Np1RSLv/card88.png",
    path2: "",
    path3: "",
  },
  {
    id: "card85",
    title: "Pure Hearts",
    cat: "Muslim",
    price: 50,
    des: "Rustic woodgrain card with lace and twine details.",
    path: "https://i.ibb.co/t4mkbbm/card89.png",
    path2: "",
    path3: "",
  },
  {
    id: "card86",
    title: "Lovely Promise",
    cat: "Muslim",
    price: 50,
    des: "Modern geometric design with gold foil and bold fonts.",
    path: "https://i.ibb.co/LZCM67p/card90.png",
    path2: "",
    path3: "",
  },
  {
    id: "card87",
    title: "Joyful Vows",
    cat: "Muslim",
    price: 50,
    des: "Floral laser-cut invitation with a blush pink ribbon.",
    path: "https://i.ibb.co/hdTSJ5P/card91.png",
    path2: "",
    path3: "",
  },
  {
    id: "card88",
    title: "Radiant Love",
    cat: "Muslim",
    price: 50,
    des: "Elegant damask pattern card with silver foil accents.",
    path: "https://i.ibb.co/zbJ9xsX/card92.png",
    path2: "",
    path3: "",
  },
  {
    id: "card89",
    title: "Sweet Together",
    cat: "Muslim",
    price: 50,
    des: "Whimsical garden-themed invitation with colorful illustrations.",
    path: "https://i.ibb.co/gTxDHKJ/card93.png",
    path2: "",
    path3: "",
  },
  {
    id: "card90",
    title: "Graceful Union",
    cat: "Muslim",
    price: 50,
    des: "Sophisticated navy and gold card with a monogrammed seal.",
    path: "https://i.ibb.co/smsPsMP/card94.png",
    path2: "",
    path3: "",
  },
  {
    id: "card91",
    title: "Dreamy Love",
    cat: "Muslim",
    price: 50,
    des: "Botanical-themed invitation with lush greenery illustrations.",
    path: "https://i.ibb.co/0fpLn6H/card95.png",
    path2: "",
    path3: "",
  },
  {
    id: "card92",
    title: "Charming Hearts",
    cat: "Muslim",
    price: 50,
    des: "Vintage-inspired card with delicate floral patterns.",
    path: "https://i.ibb.co/jhpZ3qw/card96.png",
    path2: "",
    path3: "",
  },
  {
    id: "card93",
    title: "Elegant Bliss",
    cat: "Muslim",
    price: 50,
    des: "Elegant pearl-finished invitation with embossed details.",
    path: "https://i.ibb.co/X2rCzNm/card97.png",
    path2: "",
    path3: "",
  },
  {
    id: "card94",
    title: "Pure Promise",
    cat: "Muslim",
    price: 50,
    des: "Nautical-themed card with stripes and rope accents.",
    path: "https://i.ibb.co/zb9FQKv/card98.png",
    path2: "",
    path3: "",
  },
  {
    id: "card95",
    title: "Joyous Together",
    cat: "Muslim",
    price: 50,
    des: "Floral watercolor invitation with a soft, romantic design.",
    path: "https://i.ibb.co/R6GXssj/card99.png",
    path2: "",
    path3: "",
  },
  {
    id: "card96",
    title: "Heartfelt Ceremony",
    cat: "Muslim",
    price: 50,
    des: "Luxurious velvet card with gold foil and a satin ribbon.",
    path: "https://i.ibb.co/HBBS2wZ/card100.png",
    path2: "",
    path3: "",
  },
  {
    id: "card97",
    title: "Sacred Moments",
    cat: "Muslim",
    price: 50,
    des: "Rustic kraft paper invitation with hand-drawn botanical prints.",
    path: "https://i.ibb.co/F7zwbV9/card102.png",
    path2: "",
    path3: "",
  },
  {
    id: "card98",
    title: "Lovely Hearts",
    cat: "Muslim",
    price: 50,
    des: "Modern acrylic card with sleek, minimalist typography.",
    path: "https://i.ibb.co/KDgCgqK/card101.png",
    path2: "",
    path3: "",
  },
  {
    id: "card99",
    title: " Blissful Vows",
    cat: "Muslim",
    price: 50,
    des: "Whimsical balloon-themed invitation with colorful, playful designs.",
    path: "https://i.ibb.co/JQh9Jnr/card103.png",
    path2: "",
    path3: "",
  },
  {
    id: "card100",
    title: "Radiant Moments",
    cat: "Muslim",
    price: 50,
    des: "Vintage-inspired card with sepia tones and delicate lace",
    path: "https://i.ibb.co/fHLpPp1/card104.png",
    path2: "",
    path3: "",
  },
  {
    id: "card101",
    title: "Enchanted Union",
    cat: "Muslim",
    price: 50,
    des: "Chic black and gold invitation with art deco patterns.",
    path: "https://i.ibb.co/VN3y4vr/card105.png",
    path2: "",
    path3: "",
  },
  {
    id: "card102",
    title: "Sweet Vows",
    cat: "Muslim",
    price: 50,
    des: "Rustic woodgrain invitation with hand-painted flowers.",
    path: "https://i.ibb.co/g3qhqWN/card106.png",
    path2: "",
    path3: "",
  },
  {
    id: "card103",
    title: "Joyful Together",
    cat: "Muslim",
    price: 50,
    des: "Elegant pearl-finished card with silver embossing.",
    path: "https://i.ibb.co/5B1xkTJ/card107.png",
    path2: "",
    path3: "",
  },
  {
    id: "card104",
    title: "Serene Ceremony",
    cat: "Muslim",
    price: 50,
    des: "Modern geometric design with monochrome palette.",
    path: "https://i.ibb.co/D7D94C1/card108.png",
    path2: "",
    path3: "",
  },
  {
    id: "card105",
    title: "Graceful Hearts",
    cat: "Muslim",
    price: 50,
    des: "Whimsical garden-themed invitation with fairy illustrations",
    path: "https://i.ibb.co/Cz59m2y/card109.png",
    path2: "",
    path3: "",
  },
  {
    id: "card106",
    title: "Dreamy Together",
    cat: "Muslim",
    price: 50,
    des: "Sophisticated navy and gold card with classic script",
    path: "https://i.ibb.co/ssphVbk/card110.png",
    path2: "",
    path3: "",
  },
  {
    id: "card107",
    title: "Charming Moments",
    cat: "Muslim",
    price: 50,
    des: "Floral watercolor invitation with delicate lavender blooms",
    path: "https://i.ibb.co/DbbBtt0/card112.png",
    path2: "",
    path3: "",
  },
  {
    id: "card108",
    title: "Lovely Bliss",
    cat: "Muslim",
    price: 50,
    des: "Vintage postcard-style card with travel-themed illustrations",
    path: "https://i.ibb.co/F63bkMr/card113.png",
    path2: "",
    path3: "",
  },
  {
    id: "card109",
    title: "Heartfelt Promise",
    cat: "Muslim",
    price: 50,
    des: "Elegant damask pattern invitation with gold foil.",
    path: "https://i.ibb.co/HpNDK5T/card114.png",
    path2: "",
    path3: "",
  },
  {
    id: "card110",
    title: " Elegant Love",
    cat: "Muslim",
    price: 50,
    des: "Rustic kraft paper card with hand-drawn trees and twine",
    path: "https://i.ibb.co/s2z8HzD/card115.png",
    path2: "",
    path3: "",
  },
  {
    id: "card111",
    title: "True Ceremony",
    cat: "Muslim",
    price: 50,
    des: "Glamorous glitter invitation with rose gold foil.",
    path: "https://i.ibb.co/5Fnq05F/card116.png",
    path2: "",
    path3: "",
  },
  {
    id: "card112",
    title: "Radiant Hearts",
    cat: "Muslim",
    price: 50,
    des: "Minimalist white card with clean, elegant typography.",
    path: "https://i.ibb.co/v1YxqhD/card117.png",
    path2: "",
    path3: "",
  },
  {
    id: "card113",
    title: ". Pure Moments",
    cat: "Muslim",
    price: 50,
    des: "Bohemian-style invitation with feather and floral motifs",
    path: "https://i.ibb.co/H2R3JjK/card118.png",
    path2: "",
    path3: "",
  },
  {
    id: "card114",
    title: "Joyous Vows",
    cat: "Muslim",
    price: 50,
    des: "Chic marble design with sleek black accents.",
    path: "https://i.ibb.co/brLff7S/card119.png",
    path2: "",
    path3: "",
  },
  {
    id: "card115",
    title: "Sacred Together",
    cat: "Muslim",
    price: 50,
    des: "Nautical-themed card with lighthouse and sea motifs.",
    path: "https://i.ibb.co/3MvHrZK/card120.png",
    path2: "",
    path3: "",
  },
  {
    id: "card116",
    title: "Blissful Ceremony",
    cat: "Muslim",
    price: 50,
    des: "Floral watercolor invitation with bright peonies",
    path: "https://i.ibb.co/x1PcqSb/card121.png",
    path2: "",
    path3: "",
  },
  {
    id: "card117",
    title: "Enchanted Vows",
    cat: "Muslim",
    price: 50,
    des: "Sophisticated black and silver card with intricate patterns.",
    path: "https://i.ibb.co/nrvhpzt/card122.png",
    path2: "",
    path3: "",
  },
  {
    id: "card118",
    title: "Sweet Hearts",
    cat: "Muslim",
    price: 50,
    des: "Rustic burlap invitation with hand-drawn wreath",
    path: "https://i.ibb.co/DWbBmpT/card123.png",
    path2: "",
    path3: "",
  },
  {
    id: "card119",
    title: "Lovely Union",
    cat: "Muslim",
    price: 50,
    des: "Modern acrylic card with bold, minimalist design",
    path: "https://i.ibb.co/R049kmZ/card124.png",
    path2: "",
    path3: "",
  },

  {
    id: "card120",
    title: "Enchanted Forest",
    cat: "Muslim",
    price: 50,
    des: "Elegant card with fairy-tale illustrations and gold foil accents.",
    path: "https://i.ibb.co/hcMpnXc/card125.png",
    path2: "",
    path3: "",
  },

  {
    id: "card121",
    title: "Celestial Night",
    cat: "Muslim",
    price: 50,
    des: "Midnight blue card with starry sky patterns and silver embossing.",
    path: "https://i.ibb.co/JpNjxcX/card126.png",
    path2: "",
    path3: "",
  },

  {
    id: "card122",
    title: "Eternal Elegance",
    cat: "Muslim",
    price: 50,
    des: "Classic white card with lace details and a satin ribbon",
    path: "https://i.ibb.co/wNsB22R/card127.png",
    path2: "",
    path3: "",
  },

  {
    id: "card123",
    title: "Golden Glamour",
    cat: "Muslim",
    price: 50,
    des: "Luxurious card with glittery gold and bold typography.",
    path: "https://i.ibb.co/hcgDz1p/card128.png",
    path2: "",
    path3: "",
  },

  {
    id: "card124",
    title: "Rustic Romance",
    cat: "Muslim",
    price: 50,
    des: " Kraft paper invitation with hand-drawn hearts and twine.",
    path: "https://i.ibb.co/F0xBcLS/card129.png",
    path2: "",
    path3: "",
  },

  {
    id: "card125",
    title: "Modern Chic",
    cat: "Muslim",
    price: 50,
    des: "Sleek monochrome card with minimalist typography.",
    path: "https://i.ibb.co/zfqSLsd/card130.png",
    path2: "",
    path3: "",
  },

  {
    id: "card126",
    title:
      "Boho BlissBohemian-style card with dreamcatcher illustrations and earthy tones.",
    cat: "Muslim",
    price: 50,
    des: "",
    path: "https://i.ibb.co/sW3gPdj/card131.png",
    path2: "",
    path3: "",
  },

  {
    id: "card127",
    title: "Vintage Charm",
    cat: "Muslim",
    price: 50,
    des: "Nostalgic postcard-style invitation with sepia floral patterns.",
    path: "https://i.ibb.co/4jbhNZv/card132.png",
    path2: "",
    path3: "",
  },

  {
    id: "card128",
    title: "Botanical Beauty",
    cat: "Muslim",
    price: 50,
    des: " Lush greenery illustrations on a sophisticated cream card.",
    path: "https://i.ibb.co/p3TnYGw/crad111.png",
    path2: "",
    path3: "",
  },
];

export const videoDetails = [
  {
    id: "video1",
    title: "United in Love",
    cat: "Hindu",
    price: "20",
    des: "Celebrate in Style with Our Invitation Video Collection!",
    urlWithoutPlay: "https://www.youtube-nocookie.com/embed/agSOz0DsJjo",
    urlWithPlay: "https://www.youtube-nocookie.com/embed/agSOz0DsJjo?autoplay=1&mute=0&cc_load_policy=1",
    ytID: "agSOz0DsJjo?si=wswSQ6bhvbOMwdmS",
  },

  {
    id: "video2",
    title: "The Ultimate Love Story",
    cat: "Hindu",
    price: "20",
    des: "Join Us for a Memorable Celebration – We Look Forward to Seeing You!",
    urlWithoutPlay: "https://www.youtube-nocookie.com/embed/lq-5O8zzzpg",
    urlWithPlay: "https://www.youtube-nocookie.com/embed/lq-5O8zzzpg?autoplay=1&mute=0&cc_load_policy=1",
    ytID: "lq-5O8zzzpg?si=707yi_5UIn4BtOBW",
  },

  {
    id: "video3",
    title: "A Lifetime of Love",
    cat: "Hindu",
    price: "20",
    des: "Your Presence is Requested at Our Upcoming Event!",
    urlWithoutPlay: "https://www.youtube-nocookie.com/embed/0y8-SnS6kzk",
    urlWithPlay: "https://www.youtube-nocookie.com/embed/0y8-SnS6kzk?autoplay=1&mute=0&cc_load_policy=1",
    ytID: "0y8-SnS6kzk?si=x3CEqeut4Z4P6Pkt",
  },

  {
    id: "video4",
    title: "Together in Love",
    cat: "Hindu",
    price: "20",
    des: "Come Celebrate This Special Occasion with Us!",
    urlWithoutPlay: "https://www.youtube-nocookie.com/embed/vCBJd5Gzyxc",
    urlWithPlay: "https://www.youtube-nocookie.com/embed/vCBJd5Gzyxc?autoplay=1&mute=0&cc_load_policy=1",
    ytID: "vCBJd5Gzyxc?si=ilnWLgsOUWyUMgBr",
  },

  {
    id: "video5",
    title: "Our Love Adventure",
    cat: "Hindu",
    price: "20",
    des: "We're Excited to Celebrate with You – Don't Miss Out!",
    urlWithoutPlay: "https://www.youtube-nocookie.com/embed/DSaYsNRb9TA",
    urlWithPlay: "https://www.youtube-nocookie.com/embed/DSaYsNRb9TA?autoplay=1&mute=0&cc_load_policy=1",
    ytID: "DSaYsNRb9TA?si=BtnnkyfQQjnQpfHQ",
  },

  {
    id: "video6",
    title: "The Day We Say 'I Do'",
    cat: "Hindu",
    price: "20",
    des: "A Celebration to Remember Awaits – Save the Date!",
    urlWithoutPlay: "https://www.youtube-nocookie.com/embed/agSOz0DsJjo",
    urlWithPlay: "https://www.youtube-nocookie.com/embed/agSOz0DsJjo?autoplay=1&mute=0&cc_load_policy=1",
    ytID: "agSOz0DsJjo?si=igwx4tEOg1Nj4iwr",
  },

  {
    id: "video7",
    title: "A Joyful Celebration",
    cat: "Hindu",
    price: "20",
    des: "Join Us for an Evening of Fun and Festivities!",
    urlWithoutPlay: "https://www.youtube-nocookie.com/embed/oiSzHzyGv1w",
    urlWithPlay: "https://www.youtube-nocookie.com/embed/oiSzHzyGv1w?autoplay=1&mute=0&cc_load_policy=1",
    ytID: "oiSzHzyGv1w?si=7_EoLkYjIkUB6oq-",
  },

  {
    id: "video8",
    title: "Hearts in Harmony",
    cat: "Hindu",
    price: "20",
    des: "Join Us for an Evening of Fun and Festivities!",
    urlWithoutPlay: "https://www.youtube-nocookie.com/embed/xPWu0a5Gmv0",
    urlWithPlay: "https://www.youtube-nocookie.com/embed/xPWu0a5Gmv0?autoplay=1&mute=0&cc_load_policy=1",
    ytID: "xPWu0a5Gmv0?si=MMFz0kCLLo_0AQc_",
  },

  {
    id: "video9",
    title: "The Sweetest Day",
    cat: "Hindu",
    price: "20",
    des: "Get Ready for a Special Day – We Can't Wait to Celebrate with You!",
    urlWithoutPlay: "https://www.youtube-nocookie.com/embed/LJJL32WyLEU",
    urlWithPlay: "https://www.youtube-nocookie.com/embed/LJJL32WyLEU?autoplay=1&mute=0&cc_load_policy=1",
    ytID: "LJJL32WyLEU?si=rV_4RxMbKY5qjfVo",
  },

  {
    id: "video10",
    title: "Our Fairytale Wedding",
    cat: "Hindu",
    price: "20",
    des: "Create Unforgettable First Impressions with Our Invitation Videos!",
    urlWithoutPlay: "https://www.youtube-nocookie.com/embed/AOPDn2zNxIs?",
    urlWithPlay: "https://www.youtube-nocookie.com/embed/AOPDn2zNxIs?autoplay=1&mute=0&cc_load_policy=1",
    ytID: "AOPDn2zNxIs?si=BUSY9i5NKIILz_ko",
  },

  {
    id: "video11",
    title: "An Enchanted Love",
    cat: "Hindu",
    price: "20",
    des: "Mark Your Calendar for an Event You Won't Want to Miss!",
    urlWithoutPlay: "https://www.youtube-nocookie.com/embed/qrDRDbkKtS0",
    urlWithPlay: "https://www.youtube-nocookie.com/embed/qrDRDbkKtS0?autoplay=1&mute=0&cc_load_policy=1",
    ytID: "qrDRDbkKtS0",
  },

  {
    id: "video12",
    title: "The Love Knot",
    cat: "Hindu",
    price: "20",
    des: "Captivate Your Guests with Beautiful Invitation Videos!",
    urlWithoutPlay: "https://www.youtube-nocookie.com/embed/Mladm2r8_5E",
    urlWithPlay: "https://www.youtube-nocookie.com/embed/Mladm2r8_5E?autoplay=1&mute=0&cc_load_policy=1",
    ytID: "Mladm2r8_5E",
  },

  {
    id: "video13",
    title: "The Big Celebration",
    cat: "Hindu",
    price: "20",
    des: "From Classic to Modern: Invitation Videos for Every Occasion!",
    urlWithoutPlay: "https://www.youtube-nocookie.com/embed/0CeZXIwNvJU?",
    urlWithPlay: "https://www.youtube-nocookie.com/embed/0CeZXIwNvJU?autoplay=1&mute=0&cc_load_policy=1",
    ytID: "0CeZXIwNvJU",
  },

  {
    id: "video14",
    title: "Wedding Bells",
    cat: "Hindu",
    price: "20",
    des: "Invite in Style: Explore Our Diverse Video Invitations!",
    urlWithoutPlay: "https://www.youtube-nocookie.com/embed/JmK1STnOEdQ",
    urlWithPlay: "https://www.youtube-nocookie.com/embed/JmK1STnOEdQ?autoplay=1&mute=0&cc_load_policy=1",
    ytID: "JmK1STnOEdQ",
  },

  {
    id: "video15",
    title: "The Union of Two Souls",
    cat: "Muslim",
    price: "20",
    des: "Set the Tone with Creative and Elegant Invitation Videos!",
    urlWithoutPlay: "https://www.youtube-nocookie.com/embed/Pg9wK671-w8",
    urlWithPlay: "https://www.youtube-nocookie.com/embed/Pg9wK671-w8?autoplay=1&mute=0&cc_load_policy=1",
    ytID: "Pg9wK671-w8",
  },

  {
    id: "video16",
    title: "The Perfect Union",
    cat: "Hindu",
    price: "20",
    des: "Craft the Perfect Invite with Our Stunning Video Templates!",
    urlWithoutPlay: "https://www.youtube-nocookie.com/embed/5qXczNx4OVg",
    urlWithPlay: "https://www.youtube-nocookie.com/embed/5qXczNx4OVg?autoplay=1&mute=0&cc_load_policy=1",
    ytID: "5qXczNx4OVg",
  },

  {
    id: "video17",
    title: "Hearts Entwined",
    cat: "Muslim",
    price: "20",
    des: "Transform Your Event with Unique Invitation Videos!",
    urlWithoutPlay: "https://www.youtube-nocookie.com/embed/pFzk7o_UdrA",
    urlWithPlay: "https://www.youtube-nocookie.com/embed/pFzk7o_UdrA?autoplay=1&mute=0&cc_load_policy=1",
    ytID: "pFzk7o_UdrA",
  },

  {
    id: "video18",
    title: "Love and Laughter",
    cat: "Hindu",
    price: "20",
    des: "Elevate Your Event with Personalized Invitation Videos!",
    urlWithoutPlay: "https://www.youtube-nocookie.com/embed/1vaL4HGPfSQ",
    urlWithPlay: "https://www.youtube-nocookie.com/embed/1vaL4HGPfSQ?autoplay=1&mute=0&cc_load_policy=1",
    ytID: "1vaL4HGPfSQ",
  },
];

export const faq = [
  {
    id: "q1",
    ques: "What are QR cards? ",
    ans: "QR cards are digital invitations that include a QR code. Guests can scan the QR code with their smartphones to access the event details, RSVP, and other information online.",
  },
  {
    id: "q2",
    ques: "How do QR cards work? ",
    ans: "After we design your card, we generate a unique QR code that links to your event page. Guests scan this code to view all the details.",
  },
  {
    id: "q3",
    ques: "How do I customize my QR card? ",
    ans: "You can use our online design tool to customize your card with your chosen text, colors, and images",
  },
  {
    id: "q4",
    ques: "2.	Can I upload my own design? ",
    ans: "Yes, you can upload your own design, and we will integrate the QR code into it.",
  },
  {
    id: "q5",
    ques: "3.	What information can I include in the QR code?",
    ans: "You can include details like the event date, time, location, RSVP link, and any special instructions.",
  },
  {
    id: "q6",
    ques: "4.	Can I add my wedding or event website link to the QR card? ",
    ans: "Yes, you can include your personal wedding or event website link in the QR code.",
  },
  {
    id: "q7",
    ques: "1.	What are your pricing options? ",
    ans: "Our pricing depends on the complexity of the design and the number of cards you order. Please refer to our pricing page for detailed information.",
  },
  {
    id: "q8",
    ques: "2.	What payment methods do you accept? ",
    ans: "We accept major  online payment methods.",
  },
  {
    id: "q9",
    ques: "1.	How long does it take to receive my QR card? ",
    ans: "? Digital QR cards are delivered instantly via email. If you opt for physical cards, delivery times vary based on your location.",
  },
];

export const menuOptions = [
  {
    opt: "HOME",
    route: "/",
  },
  {
    opt: "CARDS",
    route: "/cards",
  },
  {
    opt: "VIDEO",
    route: "/videos",
  },
  {
    opt: "QR DESIGN",
    route: "/qr",
  },
  {
    opt: "PHOTOGRAPHY",
    route: "/photography",
  },
  {
    opt: "CONTACT US",
    route: "/contact",
  },
];


export const hoverShadowColors = [
  " hover:shadow-purple-600",
  " hover:shadow-fuchsia-600",
  " hover:shadow-cyan-600",
  " hover:shadow-teal-600",
  " hover:shadow-amber-600",
  " hover:shadow-orange-600",
  " hover:shadow-gray-600",
  " hover:shadow-slate-600",
  " hover:shadow-red-600",
  " hover:shadow-blue-600",
  " hover:shadow-green-600",
  " hover:shadow-pink-600",
  " hover:shadow-lime-600",
  " hover:shadow-indigo-600",
  " hover:shadow-sky-600",
  " hover:shadow-yellow-600",
  "hover:shadow-emerald-600",
];
