export const cardsDetails = [
  {
    id: 1,
    title: "Sweet",
    price: "₹ 10",
    path: "./public/IMAGES/cards/card1.webp",
    des: "This card is for this this this",
    cat: "Nature",
  },
  {
    id: 2,
    title: "Sweet",
    price: "₹ 10",
    path: "./public/IMAGES/cards/card2.webp",
    des: "This card is for this this this",
    cat: "Nature",
  },
  {
    id: 3,
    title: "Sweet",
    price: "₹ 10",
    path: "./public/IMAGES/cards/card3.webp",
    des: "This card is for this this this",
    cat: "Nature",
  },
  {
    id: 4,
    title: "Sweet",
    price: "₹ 10",
    path: "./public/IMAGES/cards/card4.webp",
    des: "This card is for this this this",
    cat: "Nature",
  },
  {
    id: 5,
    title: "Sweet",
    price: "₹ 10",
    path: "./public/IMAGES/cards/card1.webp",
    des: "This card is for this this this",
    cat: "Nature",
  },
  {
    id: 6,
    title: "Sweet",
    price: "₹ 10",
    path: "./public/IMAGES/cards/card1.webp",
    des: "This card is for this this this",
    cat: "Nature",
  },
  {
    id: 7,
    title: "Sweet",
    price: "₹ 10",
    path: "./public/IMAGES/cards/card1.webp",
    des: "This card is for this this this",
    cat: "Nature",
  },
];

export const qrDetails = [
  {
    id: 100,
    title: "Sweet",
    price: "₹ 1",
    path: "./public/IMAGES/qr/qr1.jpg",
    des: "This card is for this this this",
    cat: "Nature",
  },
  {
    id: 101,
    title: "Sweet",
    price: "₹ 1",
    path: "./public/IMAGES/qr/qr2.jpg",
    des: "This card is for this this this",
    cat: "Nature",
  },
  {
    id: 102,
    title: "Sweet",
    price: "₹ 1",
    path: "./public/IMAGES/qr/qr3.jpg",
    des: "This card is for this this this",
    cat: "Nature",
  },
  {
    id: 103,
    title: "Sweet",
    price: "₹ 1",
    path: "./public/IMAGES/qr/qr4.jpg",
    des: "This card is for this this this",
    cat: "Nature",
  },
  {
    id: 104,
    title: "Sweet",
    price: "₹ 1",
    path: "./public/IMAGES/qr/qr5.jpg",
    des: "This card is for this this this",
    cat: "Nature",
  },
  {
    id: 105,
    title: "Sweet",
    price: "₹ 1",
    path: "./public/IMAGES/qr/qr6.jpg",
    des: "This card is for this this this",
    cat: "Nature",
  },
  {
    id: 106,
    title: "Sweet",
    price: "₹ 1",
    path: "./public/IMAGES/qr/qr7.jpg",
    des: "This card is for this this this",
    cat: "Nature",
  },
  {
    id: 107,
    title: "Sweet",
    price: "₹ 1",
    path: "./public/IMAGES/qr/qr8.jpg",
    des: "This card is for this this this",
    cat: "Nature",
  },
  {
    id: 108,
    title: "Sweet",
    price: "₹ 1",
    path: "./public/IMAGES/qr/qr9.jpg",
    des: "This card is for this this this",
    cat: "Nature",
  },
  {
    id: 109,
    title: "Sweet",
    price: "₹ 1",
    path: "./public/IMAGES/qr/qr10.jpg",
    des: "This card is for this this this",
    cat: "Nature",
  },
  {
    id: 110,
    title: "Sweet",
    price: "₹ 1",
    path: "./public/IMAGES/qr/qr11.jpg",
    des: "This card is for this this this",
    cat: "Nature",
  },
  {
    id: 111,
    title: "Sweet",
    price: "₹ 1",
    path: "./public/IMAGES/qr/qr12.jpg",
    des: "This card is for this this this",
    cat: "Nature",
  },
];
